#!/bin/bash

# ============================================================================
# Kangtopi Database Setup - Quick Start Guide
# ============================================================================

echo "🚀 Kangtopi Database Structure - Setup & Verification"
echo "============================================================================"

# Step 1: Run Migrations
echo ""
echo "📋 Step 1: Running Database Migrations..."
echo "Command: php artisan migrate"
echo ""
echo "Expected Output:"
echo "  ✓ Migration table created/updated"
echo "  ✓ categories table"
echo "  ✓ products table"
echo "  ✓ materials table"
echo "  ✓ quantity_tiers table"
echo "  ✓ tier_benefits table"
echo "  ✓ product_materials table"
echo "  ✓ columns added to existing tables"
echo ""

# Step 2: Run Seeders
echo "📊 Step 2: Seeding Sample Data..."
echo "Command: php artisan db:seed"
echo ""
echo "Expected Data:"
echo "  ✓ 7 Categories: Baseball, Trucker, Snapback, Bucket, Topi Rimba, Five Panel, Rope Hat"
echo "  ✓ 5 Products: Baseball Cap Classic, Baseball Cap Sport, Trucker Mesh, Snapback Original, Bucket Hat Classic"
echo "  ✓ 6 Materials: Twill 20/10, American Drill, Corduroy, Rapel 7S, Taslan, Canvas"
echo "  ✓ 3 Quantity Tiers: Starter (24-49), Medium (50-99), Bulk (100+)"
echo "  ✓ 15 Tier Benefits: 5+5+5 per tier"
echo "  ✓ 6 Estimation Factors: 3 Bordir + 2 Sablon + 1 Patch"
echo ""

# Step 3: Verify Database
echo "🔍 Step 3: Verify Database Structure"
echo ""
echo "SQL Queries to Check:"
echo ""
echo "1️⃣  Check Categories:"
echo "   SELECT id, name, slug FROM categories LIMIT 3;"
echo ""
echo "2️⃣  Check Products:"
echo "   SELECT id, name, base_price FROM products LIMIT 3;"
echo ""
echo "3️⃣  Check Materials:"
echo "   SELECT id, name, price_per_unit FROM materials LIMIT 3;"
echo ""
echo "4️⃣  Check Quantity Tiers:"
echo "   SELECT id, label, min_qty, max_qty, price_per_unit, is_negotiable FROM quantity_tiers;"
echo ""
echo "5️⃣  Check Tier Benefits:"
echo "   SELECT qt.label, COUNT(*) as benefit_count"
echo "   FROM tier_benefits tb"
echo "   JOIN quantity_tiers qt ON tb.tier_id = qt.id"
echo "   GROUP BY tb.tier_id;"
echo ""
echo "6️⃣  Check Product-Material Relations:"
echo "   SELECT COUNT(*) as total_relations FROM product_materials;"
echo ""
echo "7️⃣  Check Estimation Factors:"
echo "   SELECT name, type, extra_cost FROM estimation_factors;"
echo ""

# Step 4: Test Landing Page
echo ""
echo "🌐 Step 4: Test Landing Page"
echo "URL: http://localhost:8001/"
echo ""
echo "Checklist:"
echo "  ☐ Navbar loads correctly"
echo "  ☐ Products section displays 5 products"
echo "  ☐ Materials section displays 6 materials"
echo "  ☐ Paket section shows 3 tiers (Starter, Medium, Bulk)"
echo "  ☐ Medium tier is highlighted as 'Terpopuler'"
echo "  ☐ Estimasi calculator shows dropdowns filled"
echo "  ☐ Estimation factors show all 6 options"
echo "  ☐ Price calculation updates when selecting options"
echo ""

# Step 5: Quick Troubleshoot
echo ""
echo "🔧 Troubleshooting"
echo ""
echo "❌ If migration fails:"
echo "  → Check: php artisan migrate:status"
echo "  → Rollback: php artisan migrate:rollback"
echo "  → Fresh: php artisan migrate:fresh --seed"
echo ""
echo "❌ If seeder fails:"
echo "  → Run: php artisan tinker"
echo "  → Check: Category::count()"
echo "  → Check: Product::count()"
echo ""
echo "❌ If page shows no data:"
echo "  → Check database connection in .env"
echo "  → Verify: APP_DEBUG=true in .env"
echo "  → Check: php artisan serve output"
echo ""

echo "============================================================================"
echo "✨ Setup Complete! Your database is ready for Kangtopi e-catalog"
echo "============================================================================"
